const { YoutubeTranscript } = require('youtube-transcript');

exports.handler = async (event, context) => {
  const cors = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'GET, OPTIONS'
  };

  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: cors };
  }

  const videoId = event.queryStringParameters?.videoId;
  if (!videoId) {
    return {
      statusCode: 400,
      headers: { ...cors, 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: 'VideoId mancante' })
    };
  }

  if (!/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
    return {
      statusCode: 400,
      headers: { ...cors, 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: 'VideoId non valido' })
    };
  }

  try {
    // Try manual subtitles first (creator-uploaded)
    let transcriptItems = null;
    let usedAutoGenerated = false;

    // Attempt 1: Italian manual captions
    try {
      transcriptItems = await YoutubeTranscript.fetchTranscript(videoId, { lang: 'it' });
    } catch (_) {}

    // Attempt 2: English manual captions
    if (!transcriptItems) {
      try {
        transcriptItems = await YoutubeTranscript.fetchTranscript(videoId, { lang: 'en' });
      } catch (_) {}
    }

    // Attempt 3: Any manual captions
    if (!transcriptItems) {
      try {
        transcriptItems = await YoutubeTranscript.fetchTranscript(videoId);
      } catch (_) {}
    }

    // Attempt 4: Auto-generated Italian (ASR)
    if (!transcriptItems) {
      try {
        transcriptItems = await YoutubeTranscript.fetchTranscript(videoId, { 
          lang: 'it',
          // Some versions support autoGenerated param
        });
        usedAutoGenerated = true;
      } catch (_) {}
    }

    // Attempt 5: Auto-generated English (ASR)
    if (!transcriptItems) {
      try {
        transcriptItems = await YoutubeTranscript.fetchTranscript(videoId, { 
          lang: 'en' 
        });
        usedAutoGenerated = true;
      } catch (_) {}
    }

    if (!transcriptItems || transcriptItems.length === 0) {
      return {
        statusCode: 404,
        headers: { ...cors, 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          message: 'Nessun sottotitolo disponibile per questo video. L\'autore potrebbe avere disabilitato i sottotitoli o non sono stati generati automaticamente.' 
        })
      };
    }

    // Join all transcript pieces into single text
    const subtitles = transcriptItems
      .map(item => item.text)
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim();

    return {
      statusCode: 200,
      headers: { ...cors, 'Content-Type': 'application/json' },
      body: JSON.stringify({ subtitles, autoGenerated: usedAutoGenerated })
    };

  } catch (error) {
    console.error('Transcript error:', error.message);
    return {
      statusCode: 500,
      headers: { ...cors, 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: error.message || 'Errore nel recupero sottotitoli' })
    };
  }
};